apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: naas-user
rules:
- apiGroups:
  - ""
  - "storage.k8s.io"
  resources:
  - namespaces
  - storageclasses
  - nodes
  verbs:
  - get
  - list
